### ISSUE TITLE
the results of kitti_odometry_evaluation_tool are bad

### ISSUE THREAD

**Issue by huazai665** [donghwijung/LoRCoN-LO#3]
hello, I have run the code but got poor results. Do you use the kitti_odometry_evaluation_tool to eval your result? My test loss is 0.0139, but the results of kitti_odometry_evaluation_tool are bad. 

![image](https://user-images.githubusercontent.com/32571541/212842482-becc0638-7483-418c-9a85-16dde3873627.png)

![image](https://user-images.githubusercontent.com/32571541/212853404-4dc6f8b7-2732-455c-bf23-2f72ea0b25c1.png)

![image](https://user-images.githubusercontent.com/32571541/212853988-0fe78041-349e-414c-93a1-3e9ceecb4089.png)

**Comment by donghwijung** [comment]
Hi @huazai665
Sorry for the late answer

The reason why your errors are so large is due to the ground truth poses
In [pre-processing](https://github.com/donghwijung/LoRCoN-LO/blob/main/preprocess/transform_poses_cam_to_vel.py), we changed the coordinate of pose files which are saved as "_vel.txt" in the pose directory
If you change the ground truth pose from the original to the new files (*_vel.txt), you could get the proper results

I will attach the link for the transformed ground truth pose files [download](https://mysnu-my.sharepoint.com/:f:/g/personal/donghwijung_seoul_ac_kr/Eung5-MqWNZHldXtJfMobCEBSEFxktWVbwx6JjbJGm0N2Q?e=4Xknwl)

I hope this answer can solve your problem :)
